### ISSUE TITLE
Fail after extracting srt

### ISSUE THREAD

**Issue by Churator** [Shasoosh/embedded-subtitles-RTL-fix#1]
python3 /config/config/rev.py /data/xxxxxxx.s03e02.WEBDL-2160p.GGEZ.mkv .mkv_
arg0: /config/config/rev.py
arg1: /data/xxxxxxx.s03e02.WEBDL-2160p.GGEZ.mkv
arg2: .mkv_
Found 1 files. Starting to convert

Converting File: /data/xxxxxxx.s03e02.WEBDL-2160p.GGEZ.mkv
Traceback (most recent call last):
  File "/config/config/rev.py", line 90, in <module>
    Main()
  File "/config/config/rev.py", line 80, in Main
    ReversePuctuation(file, newFile)
  File "/config/config/rev.py", line 42, in ReversePuctuation
    for line in f:
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 4: invalid start byte

**Comment by Shasoosh** [comment]
0xa3 is ASCII. You are not running it on an embedded subtitle.
